### PR TITLE
Abort pending tasks with ObjectDisposedException

### LINKED ISSUE #3990: QUIC conformance test failure with .NET 9.0
I am getting the following errors in the dev container:

```
  IceRpc.Quic.Tests test failed with 2 error(s) and 3 warning(s) (10.6s)
    /workspaces/icerpc-csharp/tests/IceRpc.Conformance.Tests/Transports/MultiplexedConnectionConformanceTests.cs(450): error VSTEST1: IceRpc:Tests:Transports:QuicConnectionConformanceTests:Connection_dispose_aborts_pending_operations_with_operation_aborted_error: IceRpc.Conformance.Tests.MultiplexedConnectionConformanceTests.Connection_dispose_aborts_pending_operations_with_operation_aborted_error()   Expected: <IceRpc.IceRpcException>   But was:  <System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Quic.QuicConnection'.    at System.Net.Quic.QuicConnection.HandleEventShutdownComplete()    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) --- End of stack trace from previous location ---    at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)    at IceRpc.Transports.Quic.Internal.QuicMultiplexedConnection.AcceptStreamAsync(CancellationToken cancellationToken) in /workspaces/icerpc-csharp/src/IceRpc.Transports.Quic/Internal/QuicMultiplexedConnection.cs:line 33    at IceRpc.Conformance.Tests.MultiplexedConnectionConformanceTests.<>c__DisplayClass16_0.<<Connection_dispose_aborts_pending_operations_with_operation_aborted_error>b__
    /workspaces/icerpc-csharp/tests/IceRpc.Conformance.Tests/Transports/MultiplexedListenerConformanceTests.cs(127): error VSTEST1: IceRpc:Tests:Transports:QuicListenerConformanceTests:Call_accept_on_a_listener_and_then_dispose_it_fails_with_operation_aborted_error: IceRpc.Conformance.Tests.MultiplexedListenerConformanceTests.Call_accept_on_a_listener_and_then_dispose_it_fails_with_operation_aborted_error()   Expected: <IceRpc.IceRpcException>   But was:  <System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Quic.QuicListener'.    at System.Net.Quic.QuicListener.DisposeAsync()    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)    at System.Net.Quic.QuicListener.DisposeAsync()    at IceRpc.Transports.Quic.Internal.QuicMultiplexedListener.DisposeAsync() in /workspaces/icerpc-csharp/src/IceRpc.Transports.Quic/Internal/QuicMultiplexedListener.cs:line 36    at IceRpc.Conformance.Tests.MultiplexedListenerConformanceTests.Call_accept_on_a_listener_and_then_dispose_it_fails_with_operation_aborted_error() in /workspaces/icerpc-csharp/tests/IceRpc.Conformance.Tests/Transports/MultiplexedListenerConformanceTests.cs:line 124    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)    at IceRpc.Conformance.Tests.MultiplexedListenerConformanceTests.Call_
    /home/vscode/dotnet/sdk/9.0.100-preview.4.24267.66/Microsoft.TestPlatform.targets(46,5): warning : Tests triggered 2 unobserved task exceptions
    /home/vscode/dotnet/sdk/9.0.100-preview.4.24267.66/Microsoft.TestPlatform.targets(46,5): warning : 
      
      +++ Unobserved task exception System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[IceRpc.Transports.IMultiplexedStream,IceRpc.Transports.Quic.Internal.QuicMultiplexedConnection+<CreateStreamAsync>d__9]:
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'System.Net.Quic.QuicConnection'.
         at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken)
         at IceRpc.Transports.Quic.Internal.QuicMultiplexedConnection.CreateStreamAsync(Boolean bidirectional, CancellationToken cancellationToken) in /workspaces/icerpc-csharp/src/IceRpc.Transports.Quic/Internal/QuicMultiplexedConnection.cs:line 80
    /home/vscode/dotnet/sdk/9.0.100-preview.4.24267.66/Microsoft.TestPlatform.targets(46,5): warning : 
      
      +++ Unobserved task exception System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.IO.Pipelines.ReadResult,IceRpc.Transports.Quic.Internal.QuicPipeReader+<ReadAsync>d__11]:
      IceRpc.IceRpcException: An IceRpc call failed with error 'OperationAborted'.
       ---> System.Net.Quic.QuicException: Operation aborted.
         at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
         at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
         at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
         at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent)
      --- End of stack trace from previous location ---
         at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at IceRpc.Transports.Quic.Internal.QuicPipeReader.ReadAsync(CancellationToken cancellationToken) in /workspaces/icerpc-csharp/src/IceRpc.Transports.Quic/Internal/QuicPipeReader.cs:line 93
         --- End of inner exception stack trace ---
         at IceRpc.Transports.Quic.Internal.QuicPipeReader.ReadAsync(CancellationToken cancellationToken) in /workspaces/icerpc-csharp/src/IceRpc.Transports.Quic/Internal/QuicPipeReader.cs:line 97
  IceRpc.Telemetry.Tests succeeded (0.1s) → tests/IceRpc.Telemetry.Tests/net9.0/IceRpc.Telemetry.Tests.dll
  IceRpc.Tests test succeeded (11.0s)
  IceRpc.Telemetry.Tests test succeeded (0.4s)

```

### PR DESCRIPTION
**Pull request by pepone**
Fix #3990

.NET 9 updated QUIC implementation to cancel pending task with ODE, when the listener or connection are disposed. This PR updates the failing tests and align Slic with the new QUIC behavior.

### CODE REVIEW

File: src/IceRpc/Transports/Tcp/Internal/TcpListener.cs [hunk 1]
```diff
@@ -32,13 +35,20 @@ internal sealed class TcpListener : IListener<IDuplexConnection>
         }
         catch (SocketException exception)
         {
+            if (exception.SocketErrorCode == SocketError.OperationAborted)
```
Comment (pepone) [inline src/IceRpc/Transports/Tcp/Internal/TcpListener.cs:38]: I updated Tcp/Coloc listeners to do the same. Alternatively we can move this to Slic and don't update Tcp/Coloc behavior.

File: tests/IceRpc.Conformance.Tests/Transports/DuplexTransportSslAuthenticationConformanceTests.cs [hunk 2]
```diff
@@ -21,7 +21,7 @@ public async Task Ssl_client_connection_connect_fails_when_server_provides_untru
             .AddSingleton(
```
Comment (pepone) [inline tests/IceRpc.Conformance.Tests/Transports/DuplexTransportSslAuthenticationConformanceTests.cs:21]: Changes required to build conformance tests with .NET9

File: tests/IceRpc.Conformance.Tests/Transports/MultiplexedConnectionConformanceTests.cs [hunk 3]
```diff
@@ -426,9 +426,11 @@ public async Task Connection_operations_fail_with_connection_aborted_error_after
             $"The test failed with an unexpected IceRpcError {exception}");
     }
 
+#if NET9_0_OR_GREATER
+    // The QuicConnection behavior changed in .NET 9
+    // see: https://github.com/dotnet/runtime/pull/92215
     [Test]
-    [Ignore("TODO: Fix https://github.com/icerpc/icerpc-csharp/issues/3990")]
-    public async Task Connection_dispose_aborts_pending_operations_with_operation_aborted_error()
+    public async Task Connection_dispose_aborts_pending_operations_with_object_disposed_exception()
```
Comment (pepone) [inline tests/IceRpc.Conformance.Tests/Transports/MultiplexedConnectionConformanceTests.cs:433]: We just test the new behavior with .NET 9 and greater.

File: src/IceRpc.Transports.Coloc/Internal/ColocListener.cs [hunk 4]
```diff
@@ -56,6 +56,7 @@ internal class ColocListener : IListener<IDuplexConnection>
         catch (OperationCanceledException)
         {
             cancellationToken.ThrowIfCancellationRequested();
+            ObjectDisposedException.ThrowIf(_disposeCts.IsCancellationRequested, this);
```
Comment (bernardnormier) [inline src/IceRpc.Transports.Coloc/Internal/ColocListener.cs:59]: My understanding is:
 - we get OCE only when cts is canceled
 - cts can be canceled if cancellationToken is canceled (=> we throw on the line above) OR
   _disposeCts is canceled (=> 'this' was disposed). It can't be canceled for any other reason


As a result, we can never reach line 60. It would be much clearer to write this as:
```cs
cancellationToken.ThrowIfCancellationRequested();
Debug.Assert(_disposeCts.IsCancellationRequested);
throw new ObjectDisposedException(...); // comment on why we do this
```

File: src/IceRpc/Transports/Tcp/Internal/TcpListener.cs [hunk 5]
```diff
@@ -17,6 +17,9 @@ internal sealed class TcpListener : IListener<IDuplexConnection>
     private readonly MemoryPool<byte> _pool;
     private readonly Socket _socket;
 
+    // Set to 1 when the listener is disposed.
+    private int _disposed;
```
Comment (bernardnormier) [inline src/IceRpc/Transports/Tcp/Internal/TcpListener.cs:21]: I don't understand how this "int _disposed" flag works. Should it be volatile? Why not use a bool?

File: src/IceRpc/Transports/Slic/Internal/SlicConnection.cs [hunk 6]
```diff
@@ -112,6 +112,7 @@ public async ValueTask<IMultiplexedStream> AcceptStreamAsync(CancellationToken c
         catch (ChannelClosedException exception)
         {
             Debug.Assert(exception.InnerException is not null);
+            ObjectDisposedException.ThrowIf(_disposeTask is not null, this);
```
Comment (bernardnormier) [inline src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:115]: I would move this check before the Debug.Assert

File: src/IceRpc/Transports/Slic/Internal/SlicConnection.cs [hunk 7]
```diff
@@ -458,12 +459,11 @@ public async ValueTask<IMultiplexedStream> CreateStreamAsync(
 
     public ValueTask DisposeAsync()
     {
-        TryClose(new IceRpcException(IceRpcError.OperationAborted), "The connection was disposed.");
-
         lock (_mutex)
         {
             _disposeTask ??= PerformDisposeAsync();
         }
+        TryClose(new IceRpcException(IceRpcError.OperationAborted), "The connection was disposed.");
```
Comment (bernardnormier) [inline src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:466]: I don't understand this update.

For me, it makes more sense to close and then dispose - not the other way around.

It also implies that _dispatchTask is not null _only_ once _isClosed is true.

**Review by bernardnormier — COMMENTED** [review]
I am surprised there is no change to the Ice/IceRpc ProtocolConnection code that calls these transport APIs.

Even if this code already handles ObjectDisposedException / IceRpcError.OperationAborted the same way, it would make sense to remove the OperationAborted handling from IceProtocolConnection (since no QUIC/Slic for the ice protocol) and add a comment to the IceRpcProtocolConnection code (keep OperationAborted for .NET 8 QUIC support?).

File: src/IceRpc/Transports/Slic/Internal/SlicConnection.cs (hunk 7 above)
Comment (pepone) [reply src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:466]: Because TryClose calls `_acceptStreamChannel.Writer.TryComplete(exception)` which will complete the pending accept tasks before dispose.

Comment (bernardnormier) [reply src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:466]: I don't see the issue. This seems fine.

Comment (pepone) [reply src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:466]: The issue is that the pending accept task will fail with OperationAborted and we want to align it with QUIC which fails with ObjectDisposedException.

Comment (bernardnormier) [reply src/IceRpc/Transports/Slic/Internal/SlicConnection.cs:466]: Ok, what about moving the TryClose call to just after "await Task.Yield" in PerformDisposeAsync?

I think it would be more correct. _disposeTask is set but we haven't done anything else yet. And your new code is checking `_disposeTask is not null`.

File: src/IceRpc/Transports/Tcp/Internal/TcpListener.cs (hunk 5 above)
Comment (pepone) [reply src/IceRpc/Transports/Tcp/Internal/TcpListener.cs:21]: > I don't understand how this "int _disposed" flag works. Should it be volatile? 

Yes Using volatile makes sense. Here the flag allow us to see if `SocketError.OperationAborted` is throw because the listener was disposed.

> Why not use a bool?

There is no bool overload for `Interlocked.Exchange` and value types are not supported by the generic `Interlocked.Exchange` in .NET 8, this restriction was removed in .NET 9

https://github.com/dotnet/runtime/commit/41e02e5549a7954b068f342cd9bd6611ef764cc3

**Review by externl — APPROVED** [review]
Looks good to me!

**Comment by pepone** [comment]
> I am surprised there is no change to the Ice/IceRpc ProtocolConnection code that calls these transport APIs. 

I have updated the server code to expect an `ObjectDisposedException` instead of an `IceRpcException(OperationAborted)` when calling the `AcceptAsync` listener operation.

Regarding the `IceRpcProtocolConnection`, it's unaffected by the changes to `CreateStreamAsync` and `AcceptStreamAsync`. In this case, when the connection is disposed, it cancels the cancellation token passed to these operations before disposing of the transport connection. As a result, both `CreateStreamAsync` and `AcceptStreamAsync` will still fail with the expected `OperationCanceledException`. Therefore, the code doesn't need to handle neither `IceRpcException(OperationAborted)` nor `ObjectDisposedException`.

Lastly, the `IceProtocolConnection` does not use any of the updated APIs.

File: src/IceRpc/Server.cs [hunk 8]
```diff
@@ -647,9 +647,7 @@ await Task.WhenAll(
 
     /// <summary>Returns true if the <see cref="IConnectorListener.AcceptAsync" /> failure can be retried.</summary>
     private static bool IsRetryableAcceptException(Exception exception) =>
-        // The AcceptAsync call can fail with OperationAborted during shutdown if it is accepting a connection while the
-        // listener is disposed.
-        (exception is IceRpcException rpcException && rpcException.IceRpcError != IceRpcError.OperationAborted) ||
+        (exception is IceRpcException rpcException) ||
```
Comment (bernardnormier) [inline src/IceRpc/Server.cs:650]: You can simplify - maybe `exception is IceRpcException or AuthenticationException`?

**Review by bernardnormier — APPROVED** [review]

File: .github/workflows/ci.yml [hunk 9]
```diff
@@ -24,6 +33,7 @@ jobs:
         shell: bash
       - name: Test Templates
         uses: ./.github/actions/test-templates
+        if: runner.os != 'Windows'
```
Comment (bernardnormier) [inline .github/workflows/ci.yml:36]: We can't test the templates on Windows?

Comment (pepone) [reply .github/workflows/ci.yml:36]: We need to update the action see https://github.com/icerpc/icerpc-csharp/issues/3976

File: src/IceRpc.Transports.Quic/Internal/QuicMultiplexedConnection.cs [hunk 10]
```diff
@@ -89,6 +89,11 @@ public async ValueTask<IMultiplexedStream> CreateStreamAsync(
         {
             throw exception.ToIceRpcException();
         }
+        catch (ObjectDisposedException)
+        {
+            cancellationToken.ThrowIfCancellationRequested();
+            throw;
```
Comment (pepone) [inline src/IceRpc.Transports.Quic/Internal/QuicMultiplexedConnection.cs:95]: This additional fix is to ensure QUIC and Slic behave the same. CreateStreamAsync throw OperationCanceledException if ODE is received and task is already canceled.

**Comment by pepone** [comment]
> Do you mean it cancels the CTS they use and then waits for these tasks to complete before disposing the connection?

I think there was a difference here with Slic and QUIC in CreateStreamAsync.

If you cancel the cancellation token passed to CreateStreamAsync and then dispose the connection.

Slic throws OperationCancelledException, Quic throws ObjectDisposedException, I fixed Quic connection to behave as Slic adding:

```
        catch (ObjectDisposedException)
        {
            cancellationToken.ThrowIfCancellationRequested();
            throw;
        }
```

**Review by bernardnormier — APPROVED** [review]
