### PR TITLE
Fix encoding of optional custom types

### LINKED ISSUE #3812: Collections of Optional Custom Types do not Compile
### Description

For collection types, we need to generate EncodeAction functions, and the implementation of this function depends on whether the collection is of value or reference types.

For custom types, the generated code assumes it's always backed by a reference type.
If the custom type you map to is actually a value type, `slicec-cs` produces code that doesn't compile.

### Reproduction steps

For example:
```
interface Pingable {}

[cs::type("IceRpc.Slice.Tests.PingableProxy")]
custom PingableProxy

compact struct MyCompactStructWithSequenceOfNullableProxies {
    i: Sequence<PingableProxy?>
}
```
Produces the following code:
```
(ref SliceEncoder encoder, IceRpc.Slice.Tests.PingableProxy? value) =>
    PingableProxySliceEncoderExtensions.EncodePingableProxy(ref encoder, value));
```
Instead of:
```
(ref SliceEncoder encoder, IceRpc.Slice.Tests.PingableProxy? value) =>
    PingableProxySliceEncoderExtensions.EncodePingableProxy(ref encoder, value!.Value));
```

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #3812.

### CODE REVIEW

File: tools/slicec-cs/src/encoding.rs [hunk 1]
```diff
@@ -351,9 +355,10 @@ fn encode_action_body(
     let mut code = CodeBlock::default();
     let is_optional = type_ref.is_optional && !is_tagged;
 
-    let value = match (is_optional, type_ref.is_value_type()) {
-        (true, false) => "value!",
-        (true, true) => "value!.Value",
+    let value = match (is_optional, type_ref.is_value_type(), type_ref.is_reference_type()) {
```
Comment (bernardnormier) [inline tools/slicec-cs/src/encoding.rs:358]: I didn't change the logic of this code in this PR, even though it's definitely inelegant.

We compute this value here and then use "value" or value in the code below, which is pretty confusing. Not having any comment doesn't help either.

File: tools/slicec-cs/src/encoding.rs [hunk 2]
```diff
@@ -78,6 +78,8 @@ fn encode_type(
         concrete_typeref => {
             let value = if type_ref.is_optional && type_ref.is_value_type() {
                 format!("{param}.Value")
+            } else if type_ref.is_optional && !type_ref.is_reference_type() {
```
Comment (InsertCreativityHere) [inline tools/slicec-cs/src/encoding.rs:81]: Maybe add a comment about how this handles custom types?
Otherwise this branch seems redundant on the face of it.

File: tools/slicec-cs/src/encoding.rs [hunk 3]
```diff
@@ -351,9 +355,10 @@ fn encode_action_body(
     let mut code = CodeBlock::default();
     let is_optional = type_ref.is_optional && !is_tagged;
 
-    let value = match (is_optional, type_ref.is_value_type()) {
-        (true, false) => "value!",
-        (true, true) => "value!.Value",
+    let value = match (is_optional, type_ref.is_value_type(), type_ref.is_reference_type()) {
+        (true, false, true) => "value!",
+        (true, true, false) => "value!.Value",
+        (true, false, false) => "(value ?? default!)",
```
Comment (InsertCreativityHere) [inline tools/slicec-cs/src/encoding.rs:361]: I would explicitly mark this case as unreachable, since it's impossible for something to be both a value and reference type.
```suggestion
        (true, false, false) => "(value ?? default!)",
        (true, true, true) => unreachable!(),
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good!

File: tools/slicec-cs/src/encoding.rs (hunk 3 above)
Comment (pepone) [reply tools/slicec-cs/src/encoding.rs:361]: It is possible for custom, isn't it? it just mean we don't know

File: tools/slicec-cs/src/encoding.rs (hunk 2 above)
Comment (pepone) [reply tools/slicec-cs/src/encoding.rs:81]: Can we just check for custom type? I think would make the intent clear

```suggestion
            } else if type_ref.is_optional && matches!(type_ref.concrete_type(), Types::CustomType(_)) {
```

**Review by pepone — APPROVED** [review]

File: tools/slicec-cs/src/encoding.rs (hunk 3 above)
Comment (InsertCreativityHere) [reply tools/slicec-cs/src/encoding.rs:361]: The functions return true if we know-for-sure this is mapped to a value/reference type.
So custom is handled by `(_, false, false)`
Since we don't know that it's value type and we also don't know that it's a reference type.

`(_, true, true)` would mean we know something is a value type, and we also know it's a reference type, which is impossible.

File: tools/slicec-cs/src/encoding.rs (hunk 2 above)
Comment (bernardnormier) [reply tools/slicec-cs/src/encoding.rs]: I removed is_reference_type as suggested by Jose.

**Review by pepone — APPROVED** [review]
