### PR TITLE
Normalize deadline feature DateTime to UTC

### LINKED ISSUE #4421: [Audit-Medium] application-provided Local or Unspecified deadlines ca…
> **AI-generated audit finding** — this issue was opened from an automated security/correctness audit. It **has not been triaged by a human yet**; verify the reasoning, reproducibility, and severity before acting on it.

### Medium: application-provided `Local` or `Unspecified` deadlines can be enforced with the wrong timeout on the client — **CONFIRMED**

Affected code:

- [src/IceRpc.Deadline/DeadlineInterceptor.cs:58](https://github.com/icerpc/icerpc-csharp/blob/d6354eca1dc6df4b58f2115b01848c7b66a7bed4/src/IceRpc.Deadline/DeadlineInterceptor.cs#L58) — `now` captured as UTC
- [src/IceRpc.Deadline/DeadlineInterceptor.cs:61](https://github.com/icerpc/icerpc-csharp/blob/d6354eca1dc6df4b58f2115b01848c7b66a7bed4/src/IceRpc.Deadline/DeadlineInterceptor.cs#L61) — reads `deadlineFeature.Value` unchanged
- [src/IceRpc.Deadline/DeadlineInterceptor.cs:64](https://github.com/icerpc/icerpc-csharp/blob/d6354eca1dc6df4b58f2115b01848c7b66a7bed4/src/IceRpc.Deadline/DeadlineInterceptor.cs#L64) — `timeout = deadline - now` ignores `DateTime.Kind`
- [src/IceRpc.Deadline/DeadlineInterceptor.cs:83](https://github.com/icerpc/icerpc-csharp/blob/d6354eca1dc6df4b58f2115b01848c7b66a7bed4/src/IceRpc.Deadline/DeadlineInterceptor.cs#L83) — encodes via `EncodeTimeStamp`
- [src/ZeroC.Slice.Codec/TimeStampSliceEncoderExtensions.cs:12](https://github.com/icerpc/icerpc-csharp/blob/d6354eca1dc6df4b58f2115b01848c7b66a7bed4/src/ZeroC.Slice.Codec/TimeStampSliceEncoderExtensions.cs#L12) — `ToUniversalTime().Ticks`
- [src/IceRpc/Features/DeadlineFeature.cs:18](https://github.com/icerpc/icerpc-csharp/blob/d6354eca1dc6df4b58f2115b01848c7b66a7bed4/src/IceRpc/Features/DeadlineFeature.cs#L18) — feature accepts any `DateTime`

Verification:

Confirmed. `DateTime` subtraction operates on raw `Ticks` and ignores `Kind`, while `ToUniversalTime()` applies a timezone shift when `Kind` is `Local` (and treats `Unspecified` as `Local`, which is the more surprising leg). The local enforcement therefore uses raw ticks delta while the wire format uses a UTC-normalized delta, and the two diverge by exactly the local UTC offset on non-UTC systems.

Concrete example: on a UTC+2 machine, a deadline built from `DateTime.Now + 1 minute` (`Kind = Local`) yields `timeout ≈ +2h01m` at line 64 but encodes as `UtcNow + 1 minute` for the peer. The client enforces two hours too late.

Status: **Valid, Medium severity**.

Recommendation:

- Normalize the feature value to UTC at the boundary, e.g. `DateTime deadline = deadlineFeature.Value.Kind == DateTimeKind.Utc ? deadlineFeature.Value : deadlineFeature.Value.ToUniversalTime();`.
- Or reject non-UTC deadlines with `ArgumentException` in `DeadlineFeature`'s constructor, which is the better forcing-function since it also prevents the mistake at the feature-construction site.
- Add tests covering `DateTimeKind.Local` and `DateTimeKind.Unspecified`.

---

**Source report:** [src-IceRpc.Deadline-audit-2026-04-14.md](https://github.com/icerpc/icerpc-csharp-audit/blob/main/src-IceRpc.Deadline-audit-2026-04-14.md) (finding `application-provided `Local` or `Unspecified` deadlines can be enforced with the wrong timeout on the client — **CONFIRMED**`)

**Severity (auditor-assigned):** Medium

### PR DESCRIPTION
**Pull request by pepone**
Fixes #4421.

### CODE REVIEW

File: src/IceRpc/Features/DeadlineFeature.cs [hunk 1]
```diff
@@ -14,6 +14,18 @@ public sealed class DeadlineFeature : IDeadlineFeature
     public DateTime Value { get; }
 
     /// <summary>Constructs a deadline feature.</summary>
-    /// <param name="deadline">The deadline value.</param>
-    public DeadlineFeature(DateTime deadline) => Value = deadline;
+    /// <param name="deadline">The deadline value. Must have <see cref="DateTime.Kind" /> equal to
+    /// <see cref="DateTimeKind.Utc" />, or be <see cref="DateTime.MaxValue" /> (no deadline).</param>
+    /// <exception cref="ArgumentException">Thrown when <paramref name="deadline" /> is not UTC and is not
+    /// <see cref="DateTime.MaxValue" />.</exception>
+    public DeadlineFeature(DateTime deadline)
```
Comment (externl) [inline src/IceRpc/Features/DeadlineFeature.cs]: Why can't we just perform the conversion to UTC when we encode it?

File: src/IceRpc/Features/IDeadlineFeature.cs [hunk 2]
```diff
@@ -3,13 +3,14 @@
...
+/// <remarks>Once the deadline of a two-way request is reached, the caller is no longer interested in the response and
+/// the request should be discarded by the application code and IceRPC. For a one-way request, the processing of the
+/// request should be canceled once its deadline is reached. The value of this deadline feature is transmitted with
+/// requests using the <see cref="RequestFieldKey.Deadline" /> field.</remarks>
 public interface IDeadlineFeature
 {
     /// <summary>Gets the value of deadline.</summary>
-    /// <value>The deadline value. The <see cref="DateTime.MaxValue" /> means no deadline.</value>
+    /// <value>The deadline value. <see cref="DateTime.MaxValue" /> means no deadline. Otherwise a
+    /// <see cref="DateTime" /> with <c>Kind == DateTimeKind.Utc</c> representing the request expiration time.</value>
```
Comment (bernardnormier) [inline src/IceRpc/Features/IDeadlineFeature.cs]: Not sure this is necessary. I'd rather handle properly any kind of DateTime.

**Comment by pepone** [comment]
Reworked the PR to normalize the date-time to UTC on the interceptor

File: src/IceRpc/Features/DeadlineFeature.cs (hunk 1 above)
Comment (pepone) [reply src/IceRpc/Features/DeadlineFeature.cs]: Reworked the PR to do that.

File: tests/IceRpc.Deadline.Tests/DeadlineInterceptorTests.cs [hunk 3]
```diff
@@ -162,6 +162,49 @@ public void Deadline_interceptor_can_enforce_application_deadline()
...
+    /// <summary>Verifies that the interceptor encodes and enforces the same UTC instant regardless of the
+    /// deadline feature value's <see cref="DateTime.Kind" /> (see issue #4421).</summary>
+    [TestCase(DateTimeKind.Utc)]
+    [TestCase(DateTimeKind.Local)]
+    [TestCase(DateTimeKind.Unspecified)]
+    public async Task Deadline_feature_is_normalized_to_utc(DateTimeKind kind)
+    {
+        // Arrange: a hardcoded UTC target instant expressed with different Kinds.
+        DateTime targetUtc = new(2025, 6, 1, 12, 0, 0, DateTimeKind.Utc);
+        DateTime featureValue = kind switch
```
Comment (bernardnormier) [inline tests/IceRpc.Deadline.Tests/DeadlineInterceptorTests.cs]: We should provide the DateTime objects as TestCaseData.

Comment (bernardnormier) [reply tests/IceRpc.Deadline.Tests/DeadlineInterceptorTests.cs]: I would also prefer `deadline` or `deadlineValue` over `featureValue`.

**Review by bernardnormier — APPROVED** [review]

File: tests/IceRpc.Deadline.Tests/DeadlineInterceptorTests.cs (hunk 3 above)
Comment (pepone) [reply tests/IceRpc.Deadline.Tests/DeadlineInterceptorTests.cs]: Fixed as suggested

**Review by externl — APPROVED** [review]
