### PR TITLE
Review SSL authentication options cloning

### LINKED ISSUE #4357: Review authentication options clones
https://github.com/icerpc/icerpc-csharp/pull/4353#discussion_r3002792624

We need to clarify what the cloning policy should be here.

I think we should always clone options pass to Server and ClientConnection, ConnectionCache. This way if the application modifies them it doesn't has unexpected side effects.

The transports can either do the same, or only clone on write. For the transport clone on write will be my preference.

### LINKED ISSUE #4358: clientAuthenticationOptions and ssl transport
Don't we also need a check in this function (`CreateConnection`) that if `TransportName` == `ssl` that `clientAuthenticationOptions != null`?

_Originally posted by @externl in https://github.com/icerpc/icerpc-csharp/pull/4353#discussion_r3002733481_

I forget to fix that one before merging the PR.

### PR DESCRIPTION
**Pull request by pepone**
Fix #4357
Fix #4358

### CODE REVIEW

File: src/IceRpc/Transports/Quic/QuicClientTransport.cs [hunk 1]
```diff
@@ -73,15 +72,20 @@ public IMultiplexedConnection CreateConnection(
                 nameof(clientAuthenticationOptions));
         }
 
-        clientAuthenticationOptions.TargetHost ??= transportAddress.Host;
+        SslClientAuthenticationOptions? authenticationOptions = clientAuthenticationOptions;
+        if (authenticationOptions.TargetHost is null)
```
Comment (pepone) [inline src/IceRpc/Transports/Quic/QuicClientTransport.cs]: This is the only clone remaining. Here the authentication options can be used for multiple hosts, and makes sense to clone and set when not null. We do the same in the TCP client transport.

File: src/IceRpc/Transports/Tcp/TcpClientTransport.cs [hunk 2]
```diff
@@ -40,12 +40,17 @@ public IDuplexConnection CreateConnection(
         // "ssl" is only accepted for the Ice protocol, identified by the ALPN.
         if (transportAddress.TransportName == "ssl")
         {
-            if (clientAuthenticationOptions?.ApplicationProtocols is not List<SslApplicationProtocol> alpnProtocols ||
+            if (clientAuthenticationOptions is null)
```
Comment (pepone) [inline src/IceRpc/Transports/Tcp/TcpClientTransport.cs:43]: This is the fix for #4358

File: src/IceRpc/Transports/Tcp/TcpClientTransport.cs [hunk 3]
```diff
@@ -40,12 +40,17 @@ public IDuplexConnection CreateConnection(
...
+                    nameof(clientAuthenticationOptions),
+                    "The SSL client transport requires the SSL client authentication options to be set.");
+            }
+            else if (clientAuthenticationOptions.ApplicationProtocols is not List<SslApplicationProtocol> alpnProtocols ||
                 alpnProtocols.Count != 1 ||
                 alpnProtocols[0] != new SslApplicationProtocol("ice"))
             {
-                throw new NotSupportedException(
-                    "The 'ssl' transport name is only supported with the Ice protocol.");
+                throw new NotSupportedException("The 'ssl' transport name is only supported with the Ice protocol.");
```
Comment (bernardnormier) [inline src/IceRpc/Transports/Tcp/TcpClientTransport.cs]: I think Ice should be lowercase here. It's the ice and icerpc protocols.

File: src/IceRpc/Server.cs [hunk 4]
```diff
@@ -111,8 +111,7 @@ public Server(
         {
             IConnectorListener listener;
 
-            SslServerAuthenticationOptions? serverAuthenticationOptions = options.ServerAuthenticationOptions?.Clone();
-            serverAuthenticationOptions?.ApplicationProtocols = [_serverAddress.Protocol.AlpnProtocol];
+            options.ServerAuthenticationOptions?.ApplicationProtocols = [_serverAddress.Protocol.AlpnProtocol];
```
Comment (externl) [inline src/IceRpc/Server.cs]: Seems like we should do a clone of this if we're going to mutate it.

File: src/IceRpc/Transports/Tcp/TcpClientTransport.cs [hunk 5]
```diff
@@ -60,9 +65,12 @@ public IDuplexConnection CreateConnection(
                 nameof(transportAddress));
         }
 
-        SslClientAuthenticationOptions? authenticationOptions = clientAuthenticationOptions?.Clone() ??
-            (transportAddress.TransportName == "ssl" ? new SslClientAuthenticationOptions() : null);
-        authenticationOptions?.TargetHost ??= transportAddress.Host;
+        SslClientAuthenticationOptions? authenticationOptions = clientAuthenticationOptions;
```
Comment (bernardnormier) [inline src/IceRpc/Transports/Tcp/TcpClientTransport.cs]: I don't like this update. I'd rather clone all the time like we did before, not in some corner case. And I find 
`SslClientAuthenticationOptions? authenticationOptions = clientAuthenticationOptions;` error prone: it's easy to mix them up.

File: src/IceRpc/Transports/Quic/QuicClientTransport.cs [hunk 6]
```diff
@@ -73,15 +72,20 @@ public IMultiplexedConnection CreateConnection(
                 nameof(clientAuthenticationOptions));
         }
 
-        clientAuthenticationOptions.TargetHost ??= transportAddress.Host;
+        SslClientAuthenticationOptions? authenticationOptions = clientAuthenticationOptions;
```
Comment (bernardnormier) [inline src/IceRpc/Transports/Quic/QuicClientTransport.cs]: Same as for the TCP code: I'd rather Clone all the time.

File: src/IceRpc/ClientProtocolConnectionFactory.cs [hunk 7]
```diff
@@ -107,7 +107,7 @@ public IProtocolConnection CreateConnection(ServerAddress serverAddress)
         IProtocolConnection connection;
         if (serverAddress.Protocol == Protocol.Ice)
         {
-            SslClientAuthenticationOptions? authenticationOptions = _iceClientAuthenticationOptions?.Clone();
+            SslClientAuthenticationOptions? authenticationOptions = _iceClientAuthenticationOptions;
```
Comment (bernardnormier) [inline src/IceRpc/ClientProtocolConnectionFactory.cs]: For the variable name, I'd prefer clientAuthenticationOptions.

File: src/IceRpc/ClientProtocolConnectionFactory.cs [hunk 8]
```diff
@@ -130,7 +130,7 @@ public IProtocolConnection CreateConnection(ServerAddress serverAddress)
         }
         else
         {
-            SslClientAuthenticationOptions? authenticationOptions = _iceRpcClientAuthenticationOptions?.Clone();
+            SslClientAuthenticationOptions? authenticationOptions = _iceRpcClientAuthenticationOptions;
```
Comment (bernardnormier) [inline src/IceRpc/ClientProtocolConnectionFactory.cs]: Ditto

File: src/IceRpc/Server.cs (hunk 4 above)
Comment (bernardnormier) [inline src/IceRpc/Server.cs]: I'd rather keep the old code, and allow the user to reuse these ServerAuthenticationOptions for multiple servers.

File: src/IceRpc/Transports/Tcp/TcpClientTransport.cs (hunk 5 above)
Comment (externl) [reply src/IceRpc/Transports/Tcp/TcpClientTransport.cs]: I'd prefer to not make overly defensive clones all over the place personally.

Comment (externl) [reply src/IceRpc/Transports/Tcp/TcpClientTransport.cs]: Claude's assessment of dealing with these options objects, referencing how they're used in the .NET Core and Kestrel. 


> All three follow the same rule: the options object is treated as a long-lived cached value; clone it only at the point you need to diverge from the cached version. Nobody clones defensively on receipt "just in case."

Comment (pepone) [reply src/IceRpc/Transports/Tcp/TcpClientTransport.cs]: I updated https://github.com/icerpc/icerpc-csharp/issues/4357 with the description of what I think is best.

Comment (pepone) [reply src/IceRpc/Transports/Tcp/TcpClientTransport.cs]: I keep the simpler approach of cloning all the time in the client transport.

File: src/IceRpc/Transports/SslAuthenticationOptionsExtensions.cs
Comment (bernardnormier) [inline src/IceRpc/Transports/SslAuthenticationOptionsExtensions.cs]: I would rename these methods ShallowClone, like in the dotnet runtime.

File: src/IceRpc/Server.cs [hunk 9]
```diff
@@ -111,8 +111,12 @@ public Server(
         {
             IConnectorListener listener;
 
-            SslServerAuthenticationOptions? serverAuthenticationOptions = options.ServerAuthenticationOptions?.Clone();
-            serverAuthenticationOptions?.ApplicationProtocols = [_serverAddress.Protocol.AlpnProtocol];
+            SslServerAuthenticationOptions? serverAuthenticationOptions = options.ServerAuthenticationOptions;
```
Comment (bernardnormier) [inline src/IceRpc/Server.cs:114]: It's identical to the old code except with 3 more lines.

**Review by bernardnormier — APPROVED** [review]
Looks good!

File: src/IceRpc/Server.cs (hunk 9 above)
Comment (pepone) [reply src/IceRpc/Server.cs:114]: The previous  version using `?` checks twice for null.
